$(function () {
    $("#dateEntry").datepicker(
        {
            changeMonth:true,
            changeYear:true,
            showWeek:true,
            dateFormat:'yy-mm-dd',
            showButtonPanel:true,
            closeText:'关闭'
        }
    );
    $("#birthday").datepicker(
        {
            changeMonth:true,
            changeYear:true,
            showWeek:true,
            dateFormat:'yy-mm-dd',
            showButtonPanel:true,
            closeText:'关闭',
            yearRange:'1960:2010'
        }
    );
    jQuery.validator.addMethod("checkPic", function(value, element) {
        var filepath=$("#photo").val();
        //获得上传文件名
        var fileArr=filepath.split("\\");
        var fileTArr=fileArr[fileArr.length-1].toLowerCase().split(".");
        var filetype=fileTArr[fileTArr.length-1];
        //切割出后缀文件名
        if(filetype == "jpg"||filetype == "png"){
            return true;
        }else{
            return false;
        }
    }, "上传图片格式不适合");
    $("#registerForm").validate(
        {
//                    debug:true,
            rules:{
                jobNumber:{
                    required:true,
                    minlength:4
                },
                email:{
                    required:true,
                    email:true
                },
                photo:{
                    checkPic:true
                    // accept:'jpg'
                },
                education:{
                    required:true
                },
                emergencyContactPhone:{
                    required:true,
                    rangelength:[11,11]
                },
                phoneNumber:{
                    required:true,
                    rangelength:[11,11]
                },
                idNumber:{
                    required:true,
                    rangelength:[18,18]
                },
                chineseName:{
                    required:true,
                    minlength:2
                },
                birthday:{
                    required:true
                },
                clare:{
                    required:true
                },
                emergencyContact:{
                    required:true,
                    minlength:2
                },
                address:{
                    required:true,
                    minlength:10
                },
                department:{
                    required:true,
                },
                position:{
                    required:true
                },
                nationality:{
                    required:true
                },
                householdRegister:{
                    required:true
                },
                dateEntry:{
                    required:true
                },
                university:{
                    required:true
                },
                politicalOutlook:{
                    required:true
                }
            },
            messages:{
                email: "请输入一个正确的邮箱",
                photo:{
                    checkPic:"接受jpg或者png等图片"
                },
                jobNumber:{
                    required:"请输入员工工号",
                    minlength:"最少四位"
                },
                education:{
                    required:"学历"
                },
                emergencyContactPhone:{
                    required:"紧急联系人电话",
                    rangelength:"请输入11位电话号码"
                },
                phoneNumber:{
                    required:"电话号码",
                    rangelength:"请输入11位电话号码"
                },
                idNumber:{
                    required:"身份证号",
                    rangelength:"请输入18位身份证号"
                },
                chineseName:{
                    required:"中文名",
                    minlength:"最少两位"
                },
                birthday:{
                    required:"出生日期"
                },
                clare:{
                    required:"请接受公司声明"
                },
                emergencyContact:{
                    required:"紧急联系人",
                    minlength:"最少两个字符"
                },
                address:{
                    required:"住址",
                    minlength:"请填写详细"
                },
                department:{
                    required:"部门",
                },
                position:{
                    required:"职位"
                },
                nationality:{
                    required:"国籍"
                },
                householdRegister:{
                    required:"贯籍"
                },
                dateEntry:{
                    required:"入职日期"
                },
                university:{
                    required:"毕业院校"
                },
                politicalOutlook:{
                    required:"政治面貌"
                }
            }
        }
    )
})